// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9FBk1gw024tcsdJqbXmmIZSLKHg-3F4s',
    appId: '1:275271621697:web:51b939f4e2cb607b8b3ac0',
    messagingSenderId: '275271621697',
    projectId: 'employeeapp-6a763',
    authDomain: 'employeeapp-6a763.firebaseapp.com',
    databaseURL: 'https://employeeapp-6a763-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-6a763.firebasestorage.app',
    measurementId: 'G-20ZHJ3ST2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTTBkmdR1r3lAsv2cEhnEcCGgx1kdiJk',
    appId: '1:275271621697:android:8e8b918c420873ae8b3ac0',
    messagingSenderId: '275271621697',
    projectId: 'employeeapp-6a763',
    databaseURL: 'https://employeeapp-6a763-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-6a763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNhjTuI4XZy3TDNygmB0GP3bk0BMthjRw',
    appId: '1:275271621697:ios:8b6b4121b4129c148b3ac0',
    messagingSenderId: '275271621697',
    projectId: 'employeeapp-6a763',
    databaseURL: 'https://employeeapp-6a763-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-6a763.firebasestorage.app',
    iosBundleId: 'com.example.employeeMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNhjTuI4XZy3TDNygmB0GP3bk0BMthjRw',
    appId: '1:275271621697:ios:8b6b4121b4129c148b3ac0',
    messagingSenderId: '275271621697',
    projectId: 'employeeapp-6a763',
    databaseURL: 'https://employeeapp-6a763-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-6a763.firebasestorage.app',
    iosBundleId: 'com.example.employeeMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9FBk1gw024tcsdJqbXmmIZSLKHg-3F4s',
    appId: '1:275271621697:web:54c334e4eba0f8b88b3ac0',
    messagingSenderId: '275271621697',
    projectId: 'employeeapp-6a763',
    authDomain: 'employeeapp-6a763.firebaseapp.com',
    databaseURL: 'https://employeeapp-6a763-default-rtdb.firebaseio.com',
    storageBucket: 'employeeapp-6a763.firebasestorage.app',
    measurementId: 'G-4F3F41WKP4',
  );
}
